apiVersion: v1
kind: Service
metadata:
  name: kubeteach-clusterip-service
  namespace: kubeteach
spec:
  type: ClusterIP
  selector:
    app: kubeteach-webserver
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeteach-ingress
  namespace: kubeteach
spec:
  rules:
    - host: lernen.runs.onstackit.cloud
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: kubeteach-clusterip-service
                port:
                  number: 80